import Head from "next/head";
import styles from "../styles/Home.module.css";
import Directions from "../components/directions";
import APIForm from "../components/api-form";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav></nav>
      </header>
      <main className={styles.main}>
        <Directions />
        <APIForm />
        <div>
          <form action="/api/conversation" method="GET">
            <div>
              <label>Ask ChatGPT: </label>
              <input type="text" name="q" required></input>
              <button type="submit">Submit</button>
            </div>
          </form>
        </div>
      </main>
      <footer></footer>
    </>
  );
}
